### PR TITLE
Added conversion method to Color class to avoid Debugger popup

### PR DESCRIPTION
**Pull request by jgonis**
Hi Dan,

After building a Squeak vm with the Gezira bindings, I attempted to run some of the examples and got a debugger popup.  Gezira was trying to send the "asGeziraFill" message to Color objects.  This message was implemented for Forms, but not colors. I implemented it as an extension method, and simply had the color create a "uniform" GeziraFill, using itself as the argument. After this, the examples ran fine. Please let me know if you require additional changes.

Thanks,
Jeff G.

### CODE REVIEW

**Comment by damelang** [comment]
Hi Jeff,

Hats off for getting it to work! I wasn't sure anyone outside
Viewpoints would get this far :)

Your question relates to the Gezira bindings, which are the work of
Bert Freudenberg. I'm CCing him on this and he'll probably comment
soon. Comments Bert?

Sounds good to me, though.

Dan

**Comment by codefrau** [comment]
Ah, I have that method in my image but it was miscategorized, so it did not get stored in the Gezira package. Yes, patch looks good.

**Comment by jgonis** [comment]
Hi Bert,

As another note, the Gezira bindings also send the message toCamelCase to a string in the method kernelDefinitionsDo: .  I have this implemented as a Gezira extension method for Strings, but I also remember that Tobias Pape uploaded a version of toCamelCase to the inbox a while back.  This would be a general method for strings.  If you want me to add the extension method to this pull request let me know, otherwise we could grab Tobias' change from the inbox and apply it to Squeak trunk.

Thanks,
Jeff G.

**Comment by codefrau** [comment]
I just merged it into trunk. We were using the version that is in the Etoys image, though, which does not capitalize the first word. With Tobias' version you would have to change "withFirstCharacterDownshifted toCamelCase" into "toCamelCase withFirstCharacterDownshifted".

**Pull request merged**
